import { CountryCodes } from "@/types";

export default [
  {
    gold: 0,
    id: CountryCodes.FRA,
    name: "France",
    olyName: "France",
    olyName: "France",
    line: 24.5,
  },
  {
    gold: 0,
    id: CountryCodes.GBR,
    name: "Great Britain",
    olyName: "Great Britain",
    line: 16.5,
  },
  {
    gold: 0,
    id: CountryCodes.BEL,
    name: "Belgium",
    olyName: "Belgium",
    line: 3.5,
  },
  {
    gold: 0,
    id: CountryCodes.NED,
    name: "Netherlands",
    olyName: "Netherlands",
    line: 14.5,
  },
  {
    gold: 0,
    id: CountryCodes.AUS,
    name: "Australia",
    olyName: "Australia",
    line: 13.5,
  },
  {
    gold: 0,
    id: CountryCodes.ITA,
    name: "Italy",
    olyName: "Italy",
    line: 11.5,
  },
  {
    gold: 0,
    id: CountryCodes.GER,
    name: "Germany ",
    olyName: "Germany ",
    line: 10.5,
  },
  {
    gold: 0,
    id: CountryCodes.CAN,
    name: "Canada",
    olyName: "Canada",
    line: 5.5,
  },
  { gold: 0, id: CountryCodes.ESP, name: "Spain", olyName: "Spain", line: 4.5 },
  {
    gold: 0,
    id: CountryCodes.SWE,
    name: "Sweden",
    olyName: "Sweden",
    line: 4.5,
  },
  {
    gold: 0,
    id: CountryCodes.DEN,
    name: "Denmark",
    olyName: "Denmark",
    line: 3.5,
  },
  {
    gold: 0,
    id: CountryCodes.IRL,
    name: "Ireland",
    olyName: "Republic of Ireland",
    line: 2.5,
  },
  {
    gold: 0,
    id: CountryCodes.USA,
    name: "United States",
    olyName: "United States",
    line: 40.5,
  },
  {
    gold: 0,
    id: CountryCodes.CHN,
    name: "China",
    olyName: "People's Republic of China",
    line: 34.5,
  },
];
