import { OverUnder } from "@/types";

export default [
  {
    standing: 6,
    name: "Ben",
    email: "benjamin.sylvain2@gmail.com",
    fra: OverUnder.OVER,
    gbr: OverUnder.OVER,
    bel: OverUnder.OVER,
    ned: OverUnder.OVER,
    aus: OverUnder.OVER,
    ita: OverUnder.OVER,
    ger: OverUnder.UNDER,
    can: OverUnder.UNDER,
    esp: OverUnder.UNDER,
    swe: OverUnder.UNDER,
    den: OverUnder.UNDER,
    irl: OverUnder.UNDER,
    usa: OverUnder.OVER,
    chn: OverUnder.OVER,
  },
  {
    standing: 10,
    name: "Dylan",
    email: "dylan.s.pelletier@gmail.com",
    fra: OverUnder.UNDER,
    gbr: OverUnder.UNDER,
    bel: OverUnder.OVER,
    ned: OverUnder.UNDER,
    aus: OverUnder.OVER,
    ita: OverUnder.UNDER,
    ger: OverUnder.OVER,
    can: OverUnder.UNDER,
    esp: OverUnder.UNDER,
    swe: OverUnder.OVER,
    den: OverUnder.OVER,
    irl: OverUnder.OVER,
    usa: OverUnder.OVER,
    chn: OverUnder.UNDER,
  },
  {
    standing: 12,
    name: "Sam",
    email: "sam.lalezari@gmail.com",
    fra: OverUnder.UNDER,
    gbr: OverUnder.UNDER,
    bel: OverUnder.OVER,
    ned: OverUnder.UNDER,
    aus: OverUnder.OVER,
    ita: OverUnder.UNDER,
    ger: OverUnder.OVER,
    can: OverUnder.OVER,
    esp: OverUnder.OVER,
    swe: OverUnder.UNDER,
    den: OverUnder.UNDER,
    irl: OverUnder.OVER,
    usa: OverUnder.OVER,
    chn: OverUnder.OVER,
  },
  {
    standing: 11,
    name: "Ian",
    email: "ipurv547@gmail.com",
    fra: OverUnder.UNDER,
    gbr: OverUnder.OVER,
    bel: OverUnder.OVER,
    ned: OverUnder.UNDER,
    aus: OverUnder.UNDER,
    ita: OverUnder.UNDER,
    ger: OverUnder.OVER,
    can: OverUnder.OVER,
    esp: OverUnder.UNDER,
    swe: OverUnder.UNDER,
    den: OverUnder.OVER,
    irl: OverUnder.UNDER,
    usa: OverUnder.OVER,
    chn: OverUnder.OVER,
  },
  {
    standing: 7,
    name: "Lenny",
    email: "lendube29@gmail.com",
    fra: OverUnder.UNDER,
    gbr: OverUnder.OVER,
    bel: OverUnder.UNDER,
    ned: OverUnder.UNDER,
    aus: OverUnder.OVER,
    ita: OverUnder.UNDER,
    ger: OverUnder.OVER,
    can: OverUnder.UNDER,
    esp: OverUnder.OVER,
    swe: OverUnder.UNDER,
    den: OverUnder.UNDER,
    irl: OverUnder.OVER,
    usa: OverUnder.UNDER,
    chn: OverUnder.OVER,
  },
  {
    standing: 3,
    name: "Patrick",
    email: "yetman617@gmail.com",
    fra: OverUnder.UNDER,
    gbr: OverUnder.UNDER,
    bel: OverUnder.UNDER,
    ned: OverUnder.UNDER,
    aus: OverUnder.UNDER,
    ita: OverUnder.UNDER,
    ger: OverUnder.UNDER,
    can: OverUnder.UNDER,
    esp: OverUnder.UNDER,
    swe: OverUnder.UNDER,
    den: OverUnder.UNDER,
    irl: OverUnder.OVER,
    usa: OverUnder.OVER,
    chn: OverUnder.UNDER,
  },
  {
    standing: 14,
    name: "Zach",
    email: "zgolo581@gmail.com",
    fra: OverUnder.UNDER,
    gbr: OverUnder.OVER,
    bel: OverUnder.UNDER,
    ned: OverUnder.OVER,
    aus: OverUnder.OVER,
    ita: OverUnder.UNDER,
    ger: OverUnder.OVER,
    can: OverUnder.UNDER,
    esp: OverUnder.OVER,
    swe: OverUnder.UNDER,
    den: OverUnder.UNDER,
    irl: OverUnder.OVER,
    usa: OverUnder.OVER,
    chn: OverUnder.OVER,
  },
  {
    standing: 9,
    name: "DJ",
    email: "djfuhrman92@gmail.com",
    fra: OverUnder.OVER,
    gbr: OverUnder.OVER,
    bel: OverUnder.UNDER,
    ned: OverUnder.OVER,
    aus: OverUnder.OVER,
    ita: OverUnder.UNDER,
    ger: OverUnder.OVER,
    can: OverUnder.UNDER,
    esp: OverUnder.OVER,
    swe: OverUnder.OVER,
    den: OverUnder.UNDER,
    irl: OverUnder.OVER,
    usa: OverUnder.OVER,
    chn: OverUnder.UNDER,
  },
  {
    standing: 13,
    name: "Jeff",
    email: "jeff.ferguson9@gmail.com",
    fra: OverUnder.OVER,
    gbr: OverUnder.OVER,
    bel: OverUnder.UNDER,
    ned: OverUnder.UNDER,
    aus: OverUnder.OVER,
    ita: OverUnder.UNDER,
    ger: OverUnder.OVER,
    can: OverUnder.OVER,
    esp: OverUnder.OVER,
    swe: OverUnder.UNDER,
    den: OverUnder.OVER,
    irl: OverUnder.UNDER,
    usa: OverUnder.OVER,
    chn: OverUnder.OVER,
  },
  {
    standing: 8,
    name: "Shawn",
    email: "shenny1319@gmail.com",
    fra: OverUnder.UNDER,
    gbr: OverUnder.UNDER,
    bel: OverUnder.UNDER,
    ned: OverUnder.UNDER,
    aus: OverUnder.UNDER,
    ita: OverUnder.UNDER,
    ger: OverUnder.OVER,
    can: OverUnder.OVER,
    esp: OverUnder.UNDER,
    swe: OverUnder.OVER,
    den: OverUnder.UNDER,
    irl: OverUnder.UNDER,
    usa: OverUnder.OVER,
    chn: OverUnder.OVER,
  },
  {
    standing: 5,
    name: "Gavin",
    email: "gavc56@gmail.com",
    fra: OverUnder.UNDER,
    gbr: OverUnder.UNDER,
    bel: OverUnder.UNDER,
    ned: OverUnder.UNDER,
    aus: OverUnder.UNDER,
    ita: OverUnder.UNDER,
    ger: OverUnder.UNDER,
    can: OverUnder.OVER,
    esp: OverUnder.OVER,
    swe: OverUnder.OVER,
    den: OverUnder.OVER,
    irl: OverUnder.UNDER,
    usa: OverUnder.OVER,
    chn: OverUnder.UNDER,
  },
  {
    standing: 4,
    name: "Kevin",
    email: "kevinyetman31@gmail.com",
    fra: OverUnder.OVER,
    gbr: OverUnder.OVER,
    bel: OverUnder.OVER,
    ned: OverUnder.OVER,
    aus: OverUnder.OVER,
    ita: OverUnder.UNDER,
    ger: OverUnder.OVER,
    can: OverUnder.OVER,
    esp: OverUnder.OVER,
    swe: OverUnder.UNDER,
    den: OverUnder.OVER,
    irl: OverUnder.UNDER,
    usa: OverUnder.OVER,
    chn: OverUnder.UNDER,
  },
  {
    standing: 2,
    name: "Eric",
    email: "ehuot52@gmail.com",
    fra: OverUnder.UNDER,
    gbr: OverUnder.OVER,
    bel: OverUnder.OVER,
    ned: OverUnder.UNDER,
    aus: OverUnder.OVER,
    ita: OverUnder.OVER,
    ger: OverUnder.OVER,
    can: OverUnder.UNDER,
    esp: OverUnder.OVER,
    swe: OverUnder.OVER,
    den: OverUnder.UNDER,
    irl: OverUnder.UNDER,
    usa: OverUnder.OVER,
    chn: OverUnder.OVER,
  },
  {
    standing: 1,
    name: "Brandon",
    email: "jbrandonpratt@gmail.com",
    fra: OverUnder.OVER,
    gbr: OverUnder.UNDER,
    bel: OverUnder.UNDER,
    ned: OverUnder.OVER,
    aus: OverUnder.OVER,
    ita: OverUnder.UNDER,
    ger: OverUnder.UNDER,
    can: OverUnder.UNDER,
    esp: OverUnder.UNDER,
    swe: OverUnder.UNDER,
    den: OverUnder.OVER,
    irl: OverUnder.UNDER,
    usa: OverUnder.OVER,
    chn: OverUnder.OVER,
  },
];
